name: 'ITK clang-format linter'
description: 'Check for consistency with ITK Coding Style'
author: 'Matt McCormick'
inputs:
  error-message:
    description: 'Error message when style changes are required.'
    default: 'Code is inconsistent with ITK Coding Style.'
  itk-branch:
    description: 'The Git branch of the ITK repository to fetch .clang-format from.'
    default: 'master'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.error-message }}
    - ${{ inputs.itk-branch }}
